version: "3.1"
services:
  mongo:
    image: mongo:latest
    container_name: mongo_3_3
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27020:27017

    volumes:
      - ./mongo-data-4.4.4:/data/db
    command: --wiredTigerCacheSizeGB 1.5