version: "3.8"
services:
  mongo:
    image: mongo:4.4.4
    container_name: mongo_2
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=courses
    ports:
      - 27020:27017

    volumes:
      - ./mongo-data-4.4:/data/db
    command: --wiredTigerCacheSizeGB 1.5