version: "3.1"
services:
  mongo:
    image: mongo:3.7.1
    container_name: mongo_3_3
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27020:27017

    volumes:
      - ./mongo-data-3.7.1:/data/db
    command: --wiredTigerCacheSizeGB 1.5